In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.externals import joblib

In [2]:
from PIL import Image
import glob
image_list = []
for filename in glob.glob('*.jpg'):
    im = Image.open(filename)
    image_list.append(im)

In [3]:
image_list

[<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=448x298 at 0x135A75669E8>,
 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=314x209 at 0x135A76092E8>]

In [4]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [5]:
for filename in glob.iglob('*.jpg'):
    im = Image.open(filename)
    imResize = im.resize((28,28), Image.ANTIALIAS)
    imResize.save(filename , 'JPEG', quality=90)

In [6]:
image_list = []
for filename in glob.glob('*.jpg'):
    im = Image.open(filename)
    image_list.append(im)
    
image_list

[<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=28x28 at 0x135A8216F28>,
 <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=28x28 at 0x135A8216FD0>]

In [7]:


img = np.ravel(base)

df = pd.DataFrame([img])
df

0     1     2     3     4     5     6     7     8     9     10    11    \
0    87   120    63   255    73   105    55   255    81   107    68   255   

   12    13    14    15    16    17    18    19    20    21    22    23    \
0    61    80    50   255   102   118    89   255   103   131    91   255   

   24    25    26    27    28    29    30    31    32    33    34    35    \
0    97   144    90   255    65   120    55   255    54    98    35   255   

   36    37    38    39    40    41    42    43    44    45    46    47    \
0   105   128    76   255   119   130    88   255   112   134    95   255   

   48    49    50    51    52    53    54    55    56    57    58    59    \
0    99   145    98   255    83   142    88   255    84   138    80   255   

   60    61    62    63    64    65    66    67    68    69    70    71    \
0    90   131    73   255    93   129    68   255    92   130    69   255   

   72    73    74    75    76    77    78    79    80    81    82    83    \
0   109   147    86   255    93   133    73   255    95   136    76   255   

   84    85    86    87    88    89    90    91    92    93    94    95    \
0    96   137    79   255   106   147    89   255   100   139    82   255   

   96    97    98    99    100   101   102   103   104   105   106   107   \
0   106   145    88   255    88   126    67   255    89   127    68   255   

   108   109   110   111   112   113   114   115   116   117   118   119   \
0    87   127    65   255    73   113    53   255    83   120    68   255   

   120   121   122   123   124   125   126   127   128   129   130   131   \
0    73   101    60   255    55    74    42   255    91   106    75   255   

   132   133   134   135   136   137   138   139   140   141   142   143   \
0    94   119    80   255    73   113    61   255    67   117    54   255   

   144   145   146   147   148   149   150   151   152   153   154   155   \
0    61   101    39   255   107   130    78   255   126   137    94   255   

   156   157   158   159   160   161   162   163   164   165   166   167   \
0   113   134    93   255   101   139    92   255    71   118    66   255   

   168   169   170   171   172   173   174   175   176   177   178   179   \
0    77   116    61   255   109   138    84   255   101   137    76   255   

   180   181   182   183   184   185   186   187   188   189   190   191   \
0    99   137    78   255   105   145    85   255   106   146    86   255   

   192   193   194   195   196   197   198   199   200   201   202   203   \
0    86   127    67   255   105   146    88   255   109   150    92   255   

   204   205   206   207   208   209   210   211   212   213   214   215   \
0   106   145    88   255    83   121    64   255    74   112    53   255   

   216   217   218   219   220   221   222   223   224   225   226   227   \
0    72   107    49   255    84   122    61   255    72   117    58   255   

   228   229   230   231   232   233   234   235   236   237   238   239   \
0    65   105    52   255    62    94    47   255    67    88    49   255   

   240   241   242   243   244   245   246   247   248   249   250   251   \
0    89   105    69   255   107   130    88   255    87   124    72   255   

   252   253   254   255   256   257   258   259   260   261   262   263   \
0    60   105    46   255    83   124    64   255   102   131    77   255   

   264   265   266   267   268   269   270   271   272   273   274   275   \
0   106   128    79   255   103   126    80   255   114   146    97   255   

   276   277   278   279   280   281   282   283   284   285   286   287   \
0    87   124    72   255    73   103    51   255    97   120    66   255   

   288   289   290   291   292   293   294   295   296   297   298   299   \
0    93   131    72   255    91   129    72   255   108   147    90   255   

   300   301   302   303   304   305   306   307   308   309   310   311   \
0   106   145    88   255    93   134    76   255  

In [13]:

colourImg = Image.open("DSC05423.jpg")
colourPixels = colourImg.convert("RGB")
colourArray = np.array(colourPixels.getdata())

df = pd.DataFrame(colourArray, columns=["red","green","blue"])
df

red  green  blue
0     87    120    63
1     73    105    55
2     81    107    68
3     61     80    50
4    102    118    89
5    103    131    91
6     97    144    90
7     65    120    55
8     54     98    35
9    105    128    76
10   119    130    88
11   112    134    95
12    99    145    98
13    83    142    88
14    84    138    80
15    90    131    73
16    93    129    68
17    92    130    69
18   109    147    86
19    93    133    73
20    95    136    76
21    96    137    79
22   106    147    89
23   100    139    82
24   106    145    88
25    88    126    67
26    89    127    68
27    87    127    65
28    73    113    53
29    83    120    68
..   ...    ...   ...
754   89    105    68
755   76     86    49
756  253    230   224
757  249    226   218
758  235    213   202
759  249    227   214
760  237    215   202
761  241    218   204
762  236    212   200
763  221    197   185
764  230    206   196
765  228    201   194
766  247    220   213
767  251    224   217
768  255    230   221
769  236    209   198
770  209    183   170
771  201    175   160
772  170    152   128
773  138    118    94
774  140    122   100
775  131    125    99
776  110    123    93
777  123    147   115
778  119    140   109
779  122    135   107
780  120    129   100
781  114    128    95
782   84     98    63
783   77     84    50

[784 rows x 3 columns]

In [14]:
df.index = df.index + 1
df_out = df.stack()
df_out.index = df_out.index.map('{0[1]}_{0[0]}'.format)
df_out.to_frame().T

red_1  green_1  blue_1  red_2  green_2  blue_2  red_3  green_3  blue_3  \
0     87      120      63     73      105      55     81      107      68   

   red_4  green_4  blue_4  red_5  green_5  blue_5  red_6  green_6  blue_6  \
0     61       80      50    102      118      89    103      131      91   

   red_7  green_7  blue_7  red_8  green_8  blue_8  red_9  green_9  blue_9  \
0     97      144      90     65      120      55     54       98      35   

   red_10  green_10  blue_10  red_11  green_11  blue_11  red_12  green_12  \
0     105       128       76     119       130       88     112       134   

   blue_12  red_13  green_13  blue_13  red_14  green_14  blue_14  red_15  \
0       95      99       145       98      83       142       88      84   

   green_15  blue_15  red_16  green_16  blue_16  red_17  green_17  blue_17  \
0       138       80      90       131       73      93       129       68   

   red_18  green_18  blue_18  red_19  green_19  blue_19  red_20  green_20  \
0      92       130       69     109       147       86      93       133   

   blue_20  red_21  green_21  blue_21  red_22  green_22  blue_22  red_23  \
0       73      95       136       76      96       137       79     106   

   green_23  blue_23  red_24  green_24  blue_24  red_25  green_25  blue_25  \
0       147       89     100       139       82     106       145       88   

   red_26  green_26  blue_26  red_27  green_27  blue_27  red_28  green_28  \
0      88       126       67      89       127       68      87       127   

   blue_28  red_29  green_29  blue_29  red_30  green_30  blue_30  red_31  \
0       65      73       113       53      83       120       68      73   

   green_31  blue_31  red_32  green_32  blue_32  red_33  green_33  blue_33  \
0       101       60      55        74       42      91       106       75   

   red_34  green_34  blue_34  red_35  green_35  blue_35  red_36  green_36  \
0      94       119       80      73       113       61      67       117   

   blue_36  red_37  green_37  blue_37  red_38  green_38  blue_38  red_39  \
0       54      61       101       39     107       130       78     126   

   green_39  blue_39  red_40  green_40  blue_40  red_41  green_41  blue_41  \
0       137       94     113       134       93     101       139       92   

   red_42  green_42  blue_42  red_43  green_43  blue_43  red_44  green_44  \
0      71       118       66      77       116       61     109       138   

   blue_44  red_45  green_45  blue_45  red_46  green_46  blue_46  red_47  \
0       84     101       137       76      99       137       78     105   

   green_47  blue_47  red_48  green_48  blue_48  red_49  green_49  blue_49  \
0       145       85     106       146       86      86       127       67   

   red_50  green_50  blue_50  red_51  green_51  blue_51  red_52  green_52  \
0     105       146       88     109       150       92     106       145   

   blue_52  red_53  green_53  blue_53  red_54  green_54  blue_54  red_55  \
0       88      83       121       64      74       112       53      72   

   green_55  blue_55  red_56  green_56  blue_56  red_57  green_57  blue_57  \
0       107       49      84       122       61      72       117       58   

   red_58  green_58  blue_58  red_59  green_59  blue_59  red_60  green_60  \
0      65       105       52      62        94       47      67        88   

   blue_60  red_61  green_61  blue_61  red_62  green_62  blue_62  red_63  \
0       49      89       105       69     107       130       88      87   

   green_63  blue_63  red_64  green_64  blue_64  red_65  green_65  blue_65  \
0       124       72      60       105       46      83       124       64   

   red_66  green_66  blue_66  red_67  green_67  blue_67  red_68  green_68  \
0     102       131       77     106       128       79     103       126   

   blue_68  red_69  green_69  blue_69  red_70  green_70  blue_70  red_71  \
0       80     114       146       97      87       

In [15]:
colourImg = Image.open("DSC05423.jpg")

In [44]:
import mahotas
# feature-descriptor-1: Hu Moments
def fd_hu_moments(image):
    image = np.asarray(image)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    feature = cv2.HuMoments(cv2.moments(image)).flatten()
    return feature

def fd_haralick(image):
    image = np.asarray(image)
    # convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    # compute the haralick texture feature vector
    haralick = mahotas.features.haralick(gray).mean(axis=0)
    # return the result
    return haralick

In [49]:

fd_haralick(base)

array([ 1.03850838e-03,  3.63773491e+02,  6.36218017e-01,  4.98848124e+02,
        8.79985757e-02,  2.51847884e+02,  1.63161900e+03,  7.06754619e+00,
        1.00776055e+01,  1.69415515e-04,  5.10921935e+00, -4.11772293e-01,
        9.97295628e-01])

In [46]:
aa = fd_hu_moments(base)
aaa = fd_haralick(base)


In [47]:
global_feature = np.hstack([aa, aaa])

In [48]:
global_feature

array([ 1.30037712e-03,  4.53190298e-10,  4.47156606e-12,  6.59240246e-13,
       -2.09966480e-25,  7.70240167e-18, -1.11222163e-24,  1.03850838e-03,
        3.63773491e+02,  6.36218017e-01,  4.98848124e+02,  8.79985757e-02,
        2.51847884e+02,  1.63161900e+03,  7.06754619e+00,  1.00776055e+01,
        1.69415515e-04,  5.10921935e+00, -4.11772293e-01,  9.97295628e-01])

In [50]:
type(global_feature)

numpy.ndarray

In [59]:
def fd_histogram(image, mask=None):
    image = np.asarray(image)
    # convert the image to HSV color-space
    image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    # compute the color histogram
    hist  = cv2.calcHist([image], [0, 1, 2], None, [5,5,5],[0, 256, 0, 256, 0, 256])
    # normalize the histogram00
    cv2.normalize(hist, hist)
    # return the histogram
    return hist.flatten()

In [60]:
fd_histogram(base, mask=None)

array([0.        , 0.00271513, 0.01357563, 0.04615715, 0.        ,
       0.        , 0.        , 0.18191348, 0.02443614, 0.        ,
       0.        , 0.        , 0.03258152, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04344203, 0.1737681 , 0.12489583, 0.        ,
       0.        , 0.01357563, 0.8661254 , 0.39097822, 0.        ,
       0.        , 0.00543025, 0.02443614, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.04615715, 0.0923143 , 0.01629076, 0.        ,
       0.        , 0.01900589, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [61]:
aa = fd_hu_moments(base)
aaa = fd_haralick(base)
aaaa = fd_histogram(base, mask=None)

In [62]:
global_feature = np.hstack([aa, aaa, aaaa])
global_feature

array([ 1.30037712e-03,  4.53190298e-10,  4.47156606e-12,  6.59240246e-13,
       -2.09966480e-25,  7.70240167e-18, -1.11222163e-24,  1.03850838e-03,
        3.63773491e+02,  6.36218017e-01,  4.98848124e+02,  8.79985757e-02,
        2.51847884e+02,  1.63161900e+03,  7.06754619e+00,  1.00776055e+01,
        1.69415515e-04,  5.10921935e+00, -4.11772293e-01,  9.97295628e-01,
        0.00000000e+00,  2.71512661e-03,  1.35756331e-02,  4.61571515e-02,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.81913480e-01,
        2.44361386e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        3.25815193e-02,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  4.34420258e-02,  1.73768103e-01,
        1.24895826e-01,  0.00000000e+00,  0.00000000e+00,  1.35756331e-02,
        8.66125405e-01,  

In [65]:

df = pd.DataFrame(global_feature.flatten())


In [66]:
df

0
0    1.300377e-03
1    4.531903e-10
2    4.471566e-12
3    6.592402e-13
4   -2.099665e-25
5    7.702402e-18
6   -1.112222e-24
7    1.038508e-03
8    3.637735e+02
9    6.362180e-01
10   4.988481e+02
11   8.799858e-02
12   2.518479e+02
13   1.631619e+03
14   7.067546e+00
15   1.007761e+01
16   1.694155e-04
17   5.109219e+00
18  -4.117723e-01
19   9.972956e-01
20   0.000000e+00
21   2.715127e-03
22   1.357563e-02
23   4.615715e-02
24   0.000000e+00
25   0.000000e+00
26   0.000000e+00
27   1.819135e-01
28   2.443614e-02
29   0.000000e+00
..            ...
115  0.000000e+00
116  0.000000e+00
117  0.000000e+00
118  0.000000e+00
119  0.000000e+00
120  0.000000e+00
121  0.000000e+00
122  0.000000e+00
123  0.000000e+00
124  0.000000e+00
125  0.000000e+00
126  0.000000e+00
127  0.000000e+00
128  0.000000e+00
129  0.000000e+00
130  0.000000e+00
131  0.000000e+00
132  0.000000e+00
133  0.000000e+00
134  0.000000e+00
135  0.000000e+00
136  0.000000e+00
137  0.000000e+00
138  0.000000e+00
139  0.000000e+00
140  0.000000e+00
141  0.000000e+00
142  0.000000e+00
143  0.000000e+00
144  0.000000e+00

[145 rows x 1 columns]

In [67]:
df.index = df.index + 1
df_out = df.stack()
df_out.index = df_out.index.map('{0[1]}_{0[0]}'.format)
df_out.to_frame().T

0_1           0_2           0_3           0_4           0_5  \
0  0.0013  4.531903e-10  4.471566e-12  6.592402e-13 -2.099665e-25   

            0_6           0_7       0_8         0_9      0_10        0_11  \
0  7.702402e-18 -1.112222e-24  0.001039  363.773491  0.636218  498.848124   

       0_12        0_13         0_14      0_15       0_16      0_17      0_18  \
0  0.087999  251.847884  1631.619003  7.067546  10.077605  0.000169  5.109219   

       0_19      0_20  0_21      0_22      0_23      0_24  0_25  0_26  0_27  \
0 -0.411772  0.997296   0.0  0.002715  0.013576  0.046157   0.0   0.0   0.0   

       0_28      0_29  0_30  0_31  0_32      0_33  0_34  0_35  0_36  0_37  \
0  0.181913  0.024436   0.0   0.0   0.0  0.032582   0.0   0.0   0.0   0.0   

   0_38  0_39  0_40  0_41  0_42  0_43  0_44  0_45  0_46      0_47      0_48  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.043442  0.173768   

       0_49  0_50  0_51      0_52      0_53      0_54  0_55  0_56     0_57  \
0  0.124896   0.0   0.0  0.013576  0.866125  0.390978   0.0   0.0  0.00543   

       0_58  0_59  0_60  0_61  0_62  0_63  0_64  0_65  0_66  0_67  0_68  0_69  \
0  0.024436   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

   0_70  0_71      0_72      0_73      0_74  0_75  0_76      0_77  0_78  0_79  \
0   0.0   0.0  0.046157  0.092314  0.016291   0.0   0.0  0.019006   0.0   0.0   

   0_80  0_81  0_82  0_83  0_84  0_85  0_86  0_87  0_88  0_89  0_90  0_91  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

   0_92  0_93  0_94  0_95  0_96  0_97  0_98      0_99  0_100  0_101  0_102  \
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  0.010861    0.0    0.0    0.0   

   0_103  0_104  0_105  0_106  0_107  0_108  0_109  0_110  0_111  0_112  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   0_113  0_114  0_115  0_116  0_117  0_118  0_119  0_120  0_121  0_122  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   0_123  0_124  0_125  0_126  0_127  0_128  0_129  0_130  0_131  0_132  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   0_133  0_134  0_135  0_136  0_137  0_138  0_139  0_140  0_141  0_142  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   0_143  0_144  0_145  
0    0.0    0.0    0.0